steps:
    - name: 'gcr.io/cloud-builders/git'
      entrypoint: bash
      id: 'Checkout Code'
      args:
        - '-c'
        - |
          git clone https://github.com/bipinupd/DLPTemplates.git
          cd DLPTemplates/
          if [[ "$_DIFFBUILD" == "true" ]];
          then
            git checkout $BRANCH_NAME
            git pull origin $BRANCH_NAME
            git diff --name-only $BRANCH_NAME master > "/workspace/dlp-diff.txt"
          else
            git checkout master
            git pull origin master
            ls deIdentify_templates/*.json > /workspace/dlp-diff.txt
            ls inspect_templates/*.json >> /workspace/dlp-diff.txt
          fi
    - name: 'gcr.io/${PROJECT_ID}/dlp_image'
      entrypoint: bash
      args:
        - '-c'
        - |
          cd /workspace/DLPTemplates/tests
          pytest -m build -s
      id: 'Test'
    - name: 'gcr.io/${PROJECT_ID}/dlp_image'
      entrypoint: bash
      args:
        - '-c'
        - |
          bash /workspace/DLPTemplates/scripts/package.sh
          cat /workspace/package/DLPTemplates/deIdentify_templates_to_delete
      id: 'Deployable DLP artifacts'
artifacts:
  objects:
    location: 'gs://${_ARTIFACT_REPO}/${SHORT_SHA}'
    paths: ['/workspace/package/DLPTemplates.zip']