steps:
    - name: 'gcr.io/cloud-builders/git'
      entrypoint: bash
      id: 'Checkout Code'
      args:
        - '-c'
        - |
          git clone https://github.com/bipinupd/DLPTemplates.git
          cd DLPTemplates/
          git checkout $_BRANCHNAME
          git config pull.rebase false
          git pull origin $_BRANCHNAME
          git diff --name-only $_BRANCHNAME master -- / > /workspace/dlp-diff.txt
          git diff master $_BRANCHNAME --name-only --diff-filter=D > /workspace/deleted_files.txt
    - name: 'gcr.io/bipin-dev/dp-test-python'
      entrypoint: bash
      args:
        - '-c'
        - |
          cd /workspace/DLPTemplates/tests
          pytest -m build -s
      id: 'Test'
    - name: 'gcr.io/bipin-dev/dlp_image_build'
      entrypoint: bash
      args:
        - '-c'
        - |
          bash /workspace/DLPTemplates/scripts/package.sh
      id: 'Deployable DLP artifacts'
artifacts:
  objects:
    location: 'gs://${_ARTIFACT_REPO}/${SHORT_SHA}'
    paths: ['/workspace/package/DLPTemplates.zip']