steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    id: 'Create Keyring If Not Present'
    args:
      - '-c'
      - |
        count=$(gcloud kms keyrings list --project=${_PROJECTID} --location=$_LOCATION --filter=$_KEYRING | wc -l)
        if [ $count == 0 ]; then
          gcloud kms keyrings create $_KEYRING --location=$_LOCATION --project=${_PROJECTID}
        fi
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        count=$(gcloud kms keys list --project=$_PROJECTID --keyring=$_KEYRING --location=$_LOCATION --filter=$_KEY | wc -l)
        if [ $count == 0 ]; then
         gcloud kms keys create $_KEY --project=$_PROJECTID --keyring=$_KEYRING --location=$_LOCATION --purpose=encryption --replication-policy=automatic
        fi        
        if [ $_ROTATE_KEY == true ]; then
         gcloud kms keys versions create --project=$_PROJECTID --key=$_KEY --keyring=$_KEYRING --location=$_LOCATION --primary
        fi
    id: 'Create or Rotate the Key'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        curl -X POST -H "Content-Type: application/json" \
            -H "Authorization: Bearer $(gcloud auth print-access-token)" \
            "https://cloudkms.googleapis.com/v1/projects/${_PROJECTID}/locations/${_LOCATION}/keyRings/${_KEYRING}/cryptoKeys/${_KEY}:encrypt" \
            -d '{"plaintext":"${_DEK}"}' \
            -o key-temp.json
        cat ./key-temp.json
        secret_count=$(gcloud secrets list --filter=${_KEY} | wc -l)
        if [ $secret_count == 0 ]; then
          gcloud secrets create ${_KEY} --data-file=./key-temp.json --project=${_PROJECTID} --replication-policy=automatic
        fi
        gcloud secrets versions add ${_KEY} --data-file=./key-temp.json --project=${_PROJECTID}
    id: 'Create Wrapped Key & Store in Secret Manager'
