steps:
    - name: 'gcr.io/cloud-builders/git'
      entrypoint: bash
      id: 'Checkout Code'
      args:
        - '-c'
        - |
          git clone https://github.com/bipinupd/DLPTemplates.git
          cd DLPTemplates/
          git checkout master
          ls  deidentify_templates/* > /workspace/dlp-diff.txt
          ls  inspect_templates/* >> /workspace/dlp-diff.txt
          cat /workspace/dlp-diff.txt
    - name: 'gcr.io/bipin-dev/dp-test-python'
      entrypoint: bash
      args:
        - '-c'
        - |
          cd /workspace/dDLPTemplates/tests
          pytest -m build -s
      id: 'Test'
    - name: 'gcr.io/bipin-dev/zip'
      entrypoint: bash
      args:
        - '-c'
        - |
          bash /workspace/DLPTemplates/scripts/package.sh
      id: 'Deployable DLP artifacts'
artifacts:
  objects:
    location: 'gs://${_ARTIFACT_REPO}/${SHORT_SHA}'
    paths: ['/workspace/dlp.zip']